# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Inicio
    url: /#top
    weight: 10
  - name: Calendario
    url: /#features
    weight: 20
  - name: Horario
    url: /#solutions
    weight: 30
  - name: Ubicación
    url: /#location
    weight: 40
  - parent: Organizadores
    name: Blog
    url: blog/
